package org.fifties.housewife.bi.lexicon.extraction;

import java.util.List;

import org.fifties.housewife.bi.lexicon.SkosConcept;

/**
 * Renders arXiv's subject taxonomy as the TSV the lexicon bundles: a provenance header naming the module
 * revision it was read at and the terms it is published on, then the concepts in the shape every taxonomy
 * here is normalised to.
 */
public class ArxivTaxonomyTsv {

    private final SkosTsv rows = new SkosTsv();

    public String render(final List<SkosConcept> concepts, final String source) {
        return header(concepts.size(), source) + rows.render(concepts);
    }

    private static String header(final int count, final String source) {
        return """
                # arXiv's subject taxonomy as a functional taxonomy of research: ten groups, the archives
                # inside them and the categories inside those, each category carrying the description arXiv
                # states its subject matter in. Like every functional taxonomy here it is a distribution to
                # compare against and not a vocabulary to match — nobody writes cs.CL in code, and nobody
                # writes Computation and Language either. What a scope is compared on is the description:
                # cs.IR covers indexing, dictionaries, retrieval, content and analysis, and a repository
                # about those things reads like that sentence whether or not it ever quotes a word of it.
                #
                # Columns:\s""" + SkosTsv.COLUMNS + """
                .
                # broader is the archive a category is stated inside, the group an archive is stated inside,
                # and empty for a group; module is the group a concept rolls up to. altLabel is the alias
                # arXiv publishes beside a name — cs.CL is also cmp-lg, math.IT is also cs.IT — which is the
                # publisher stating synonymy rather than anyone grouping by hand. A group, archive or
                # category arXiv does not state as live is not carried, and neither is the group it marks as
                # a test.
                #
                # Source: arXiv's own taxonomy definitions, the module its software classifies by, read from
                #  \s""" + source + """
                .
                # Licence: MIT, Copyright (c) 2026 arXiv, Inc.
                #   (https://github.com/arxiv/arxiv-base/blob/develop/LICENSE). The identifiers, names and
                #   subject descriptions are arXiv's statement of its own classification, read from the
                #   software that applies it — the same ground on which this library reads a query engine's
                #   function catalogue out of the engine.
                # Generated by ArxivTaxonomyExtraction:\s""" + count + " concepts.\n";
    }
}
