package org.fifties.housewife.bi.lexicon.extraction;

import java.util.List;

import org.fifties.housewife.bi.lexicon.SkosConcept;

/**
 * Renders the Cybersecurity Framework as the TSV the lexicon bundles: a provenance header naming the OSCAL
 * edition it was read at and the terms it is published on, then the concepts in the shape every taxonomy
 * here is normalised to.
 *
 * <p>The header says what this file is for as much as where it came from, because a functional taxonomy
 * used as a term list would be a mistake nothing in the format itself would catch.
 */
public class NistCsfTsv {

    private final SkosTsv rows = new SkosTsv();

    public String render(final List<SkosConcept> concepts, final String version, final String source) {
        return header(concepts.size(), version, source) + rows.render(concepts);
    }

    private static String header(final int count, final String version, final String source) {
        return """
                # The NIST Cybersecurity Framework 2.0 as a functional taxonomy: six functions, the
                # categories under each of them and the subcategories under those, with the outcome NIST
                # states each one as. This is not a vocabulary to match against identifiers — nobody writes
                # GV.OC-01, and nobody writes Organizational Context either. It is a published partition of
                # what a security function does, and the sentence defining each part is what a body of code
                # can be compared against as a distribution rather than searched for as a term.
                #
                # Columns:\s""" + SkosTsv.COLUMNS + """
                .
                # broader is empty for a function, the framework's own top level; module is the function a
                # concept rolls up to; altLabel is the label NIST publishes beside a title wherever it
                # publishes a different one, and empty where it publishes none. Concepts NIST states as
                # withdrawn are not carried, which is what leaves 1.1's categories out.
                #
                # Source: NIST_CSF_v2.0_catalog.json at version\s""" + version + """
                , the OSCAL edition
                #   NIST publishes of the Cybersecurity Framework 2.0, read from
                #  \s""" + source + """
                .
                # Licence: public domain. The catalogue is a work of the United States government, and NIST
                #   additionally waives copyright and related rights worldwide through CC0 1.0
                #   (https://github.com/usnistgov/oscal-content/blob/main/LICENSE.md). The framework's own
                #   words are quoted as NIST publishes them, and NIST states no endorsement of any use.
                # Generated by NistCsfExtraction:\s""" + count + " concepts.\n";
    }
}
