package org.fifties.housewife.bi.lexicon.extraction;

import java.util.List;

import org.fifties.housewife.bi.lexicon.SkosConcept;

/**
 * Renders OLiA's classes as the TSV the lexicon bundles: a provenance header naming the revision the
 * ontology was read at and the terms it is published on, then the concepts in the shape every taxonomy here
 * is normalised to.
 */
public class OliaTermsTsv {

    private final SkosTsv rows = new SkosTsv();

    public String render(final List<SkosConcept> concepts, final String source) {
        return header(concepts.size(), source) + rows.render(concepts);
    }

    private static String header(final int count, final String source) {
        return """
                # The Ontologies of Linguistic Annotation, as the terms a program writing about grammar
                # actually writes. Unlike the functional taxonomies bundled beside it this one is meant to be
                # matched: its concepts are already identifiers — AdjectivePhrase, Determiner, Acronym,
                # CommonNoun — so a match is identifier to identifier with no English in between, which is
                # the ground sql-functions.tsv states. A term is the fragment of the class's own URI, and no
                # word of it was chosen here.
                #
                # Columns:\s""" + SkosTsv.COLUMNS + """
                .
                # broader is the first superclass the ontology states by name, and empty where that
                # superclass belongs to an ontology this file imports rather than carries — a roll-up must
                # not climb to a concept nothing here can answer for. altLabel is the rdfs:label where it
                # says something the identifier does not.
                #
                # definition is the ontology's own rdfs:comment and note is its own owl:versionInfo — what a
                # concept means, and which scheme its publisher took it from. Both were written empty in
                # every earlier revision of this file on the belief that OLiA states its meaning only
                # through its hierarchy. It does not: the document carries 1,272 definitions across 1,216 of
                # these concepts and 949 provenance notes across 780 of them, and they were discarded here.
                # Nothing is paraphrased and no gloss is written; the text is the publisher's, with runs of
                # whitespace collapsed to one space so a row stays a row. Where the ontology states a
                # property twice for one concept the statements are joined with " | " in the order it wrote
                # them, and an exact repeat counts once. One definition, on AdnominalConstituent, the
                # ontology marks xml:lang="de"; it is carried like the rest, because refusing it would be
                # this file deciding what the publisher may say.
                #
                # Source: OLiA's core ontology olia.owl, read from
                #  \s""" + source + """
                .
                # Licence: CC BY 3.0 Unported, stated by the ontology itself (dct:license
                #   https://creativecommons.org/licenses/by/3.0/) and in the repository's own LICENSE.data.
                #   Attribution, as the licence requires: Ontologies of Linguistic Annotation (OLiA),
                #   Christian Chiarcos and the Applied Computational Linguistics lab, Goethe University
                #   Frankfurt. The repository's code is Apache-2.0 and its data is not; this file is data.
                # Generated by OliaTermsExtraction:\s""" + count + " terms.\n";
    }
}
