package org.fifties.housewife.bi.lexicon.extraction;

import java.util.List;

import org.fifties.housewife.bi.lexicon.SkosConcept;

/**
 * Renders OLiA's classes as the TSV the lexicon bundles: a provenance header naming the revision the
 * ontology was read at and the terms it is published on, then the concepts in the shape every taxonomy here
 * is normalised to.
 */
public class OliaTermsTsv {

    private final SkosTsv rows = new SkosTsv();

    public String render(final List<SkosConcept> concepts, final String source) {
        return header(concepts.size(), source) + rows.render(concepts);
    }

    private static String header(final int count, final String source) {
        return """
                # The Ontologies of Linguistic Annotation, as the terms a program writing about grammar
                # actually writes. Unlike the functional taxonomies bundled beside it this one is meant to be
                # matched: its concepts are already identifiers — AdjectivePhrase, Determiner, Acronym,
                # CommonNoun — so a match is identifier to identifier with no English in between, which is
                # the ground sql-functions.tsv states. A term is the fragment of the class's own URI, and no
                # word of it was chosen here.
                #
                # Columns:\s""" + SkosTsv.COLUMNS + """
                .
                # broader is the first superclass the ontology states by name, and empty where that
                # superclass belongs to an ontology this file imports rather than carries — a roll-up must
                # not climb to a concept nothing here can answer for. altLabel is the rdfs:label where it
                # says something the identifier does not. definition is empty: OLiA states its meaning
                # through its hierarchy and its links to annotation schemes, not in prose, and inventing a
                # gloss would be this library writing the vocabulary it is supposed to be citing.
                #
                # Source: OLiA's core ontology olia.owl, read from
                #  \s""" + source + """
                .
                # Licence: CC BY 3.0 Unported, stated by the ontology itself (dct:license
                #   https://creativecommons.org/licenses/by/3.0/) and in the repository's own LICENSE.data.
                #   Attribution, as the licence requires: Ontologies of Linguistic Annotation (OLiA),
                #   Christian Chiarcos and the Applied Computational Linguistics lab, Goethe University
                #   Frankfurt. The repository's code is Apache-2.0 and its data is not; this file is data.
                # Generated by OliaTermsExtraction:\s""" + count + " terms.\n";
    }
}
