package org.fifties.housewife.bi.lexicon.extraction;

import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Renders the topic hierarchy as the TSV the lexicon bundles: a provenance header naming the revision the
 * map was read at, then one sorted row per topic with the broader topics it generalises to.
 */
public class TopicHierarchyTsv {

    public String render(final Map<String, Set<String>> broaderByTopic, final String revision) {
        final StringBuilder text = new StringBuilder(header(broaderByTopic.size(), revision));
        broaderByTopic.entrySet().stream()
                .sorted(Map.Entry.comparingByKey())
                .forEach(entry -> text.append(entry.getKey()).append('\t')
                        .append(entry.getValue().stream().sorted().collect(Collectors.joining(",")))
                        .append('\n'));
        return text.toString();
    }

    private static String header(final int count, final String revision) {
        return """
                # Wiktionary topic hierarchy, one row per topic: the topic and the broader topics it
                # generalises to, comma-separated. This is the map that produced the broader labels already
                # sitting in wiktionary-topics.tsv — wiktextract applies it transitively as it extracts a
                # sense's topics, so a sense labelled computing arrives carrying engineering, mathematics,
                # natural-sciences, physical-sciences and sciences besides. Reading it back is what tells a
                # label a headword states from one another of its labels already implies.
                #
                # Source: wiktextract's own topic_generalize_map, read from
                #  \s""" + revision + """
                .
                # Licence: MIT, Copyright (c) 2018-2020 Tatu Ylonen
                #   (https://github.com/tatuylonen/wiktextract/blob/master/LICENSE). The map is
                #   wiktextract's own source, not Wiktionary content, so the CC BY-SA terms carried by the
                #   topic vocabulary it labels do not attach to this file.
                # Generated by TopicHierarchyExtraction:\s""" + count + " topics.\n";
    }
}
