package org.fifties.housewife.bi.lexicon.extraction;

import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Renders the topic vocabulary as the TSV the lexicon bundles: a provenance header carrying source,
 * licence and count, then one sorted row per headword with its topics sorted and comma-joined.
 */
public class TopicTsv {

    public String render(final Map<String, Set<String>> topicsByWord) {
        final StringBuilder text = new StringBuilder(header(topicsByWord.size()));
        topicsByWord.entrySet().stream()
                .sorted(Map.Entry.comparingByKey())
                .forEach(entry -> text.append(entry.getKey()).append('\t')
                        .append(entry.getValue().stream().sorted().collect(Collectors.joining(",")))
                        .append('\n'));
        return text.toString();
    }

    private static String header(final int count) {
        return """
                # Wiktionary topic vocabulary, one row per headword: the word (multi-word phrases carry
                # underscores, the written form the bundled WordNet resources use) and the union of topic
                # labels across its senses, comma-separated. The dictionary saying which domains claim the
                # word — membership is a vote's evidence, never a decision.
                #
                # Source: Wiktionary (https://en.wiktionary.org/), read from the wiktextract JSONL published
                #   at kaikki.org (https://kaikki.org/dictionary/English/); Tatu Ylonen: "Wiktextract:
                #   Wiktionary as Machine-Readable Structured Data", LREC 2022.
                # Licence: this data file is derived from Wiktionary content and is distributed under
                #   CC BY-SA (https://creativecommons.org/licenses/by-sa/4.0/). The licence attaches to
                #   this file, not to the code that reads or produced it.
                # Generated by WiktionaryExtraction:\s""" + count + " words.\n";
    }
}
