package org.fifties.housewife.bi.lexicon.extraction;

import java.util.List;

import org.fifties.housewife.bi.lexicon.SkosConcept;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertAll;

class NistCsfTsvTest {

    private static final List<SkosConcept> CONCEPTS = List.of(new SkosConcept("GV", "GOVERN", "GOVERN (GV)",
            "", "function", "GV", "Risk is governed", ""));

    private static final String SOURCE = "https://example.invalid/NIST_CSF_v2.0_catalog.json";

    private final String rendered = new NistCsfTsv().render(CONCEPTS, "1.2.0", SOURCE);

    @Test
    void statesWhereTheFrameworkCameFromAndOnWhatTerms() {
        assertAll(
                () -> assertThat(rendered).contains("# Source: NIST_CSF_v2.0_catalog.json at version 1.2.0"),
                () -> assertThat(rendered).contains(SOURCE),
                () -> assertThat(rendered).contains("# Licence: public domain"),
                () -> assertThat(rendered).contains("CC0 1.0"));
    }

    @Test
    void namesTheColumnsTheRowsAreWrittenIn() {
        assertThat(rendered).contains("# Columns: " + SkosTsv.COLUMNS);
    }

    @Test
    void saysTheFrameworkIsADistributionToCompareAgainstAndNotATermList() {
        assertThat(rendered).contains("not a vocabulary to match against identifiers");
    }

    @Test
    void countsTheConceptsItWrote() {
        assertThat(rendered).contains("# Generated by NistCsfExtraction: 1 concepts.");
    }

    @Test
    void writesEveryConceptBelowTheHeader() {
        assertThat(rendered).endsWith("GV\tGOVERN\tGOVERN (GV)\t\tfunction\tGV\tRisk is governed\t\n");
    }
}
