package io.github.fiftieshousewife.bi.lexicon.extraction;

import java.util.Collection;
import java.util.Comparator;
import java.util.List;

/**
 * Renders the extracted senses as the TSV the lexicon bundles: a provenance header carrying source,
 * licence and count, then one sorted row per distinct sense.
 */
public class AbbreviationTsv {

    public String render(final Collection<AbbreviationSense> senses) {
        final List<AbbreviationSense> rows = senses.stream()
                .distinct()
                .sorted(Comparator.comparing(AbbreviationSense::token)
                        .thenComparing(AbbreviationSense::expansion)
                        .thenComparing(AbbreviationSense::kind))
                .toList();
        final StringBuilder text = new StringBuilder(header(rows.size()));
        rows.forEach(row -> text.append(row.token()).append('\t')
                .append(row.expansion()).append('\t')
                .append(row.kind()).append('\t')
                .append(String.join(",", row.topics())).append('\t')
                .append(row.quantity()).append('\n'));
        return text.toString();
    }

    private static String header(final int count) {
        return """
                # Wiktionary abbreviation senses, one row per cited reading: the token, the expansion its
                # entry names, the kind of shortening the sense declares (abbreviation, initialism, acronym,
                # clipping or symbol), the sense's topic labels (comma-separated, often empty), and — for a
                # unit symbol — the quantity the standard says the unit measures, blank for every other
                # kind. A token with several cited expansions keeps one row each — this file cites usage,
                # the reader votes.
                #
                # Source: Wiktionary (https://en.wiktionary.org/), read from the wiktextract JSONL published
                #   at kaikki.org: the English extract (https://kaikki.org/dictionary/English/) and the
                #   Translingual extract (https://kaikki.org/dictionary/Translingual/), which carries the
                #   unit symbols; Tatu Ylonen: "Wiktextract: Wiktionary as Machine-Readable Structured
                #   Data", LREC 2022.
                # Licence: this data file is derived from Wiktionary content and is distributed under
                #   CC BY-SA (https://creativecommons.org/licenses/by-sa/4.0/). The licence attaches to
                #   this file, not to the code that reads or produced it.
                # Generated by WiktionaryAbbreviationExtraction:\s""" + count + " senses.\n";
    }
}
