package io.github.fiftieshousewife.bi.lexicon.extraction;

import java.util.List;

import io.github.fiftieshousewife.bi.lexicon.SkosConcept;

/**
 * Renders BIAN's service domains as the TSV the lexicon bundles: a provenance header naming the revision
 * the artefacts were read at and the digest that pins the specification set, then the domains in the shape
 * every taxonomy here is normalised to.
 */
public class BianServiceDomainsTsv {

    private final SkosTsv rows = new SkosTsv();

    public String render(final List<SkosConcept> concepts, final String source, final String digest) {
        return header(concepts.size(), source, digest) + rows.render(concepts);
    }

    private static String header(final int count, final String source, final String digest) {
        return """
                # The BIAN Service Landscape as a functional taxonomy of what a bank does: service domains,
                # the business domain each is stated inside and the business area that holds it, each carrying
                # the role definition BIAN states its purpose in and the example of use it states beside it.
                # Like every functional taxonomy here it is a distribution to compare against: nobody writes
                # AccountReconciliation as a term of art in code.
                #
                """
                + "# Columns: " + SkosTsv.COLUMNS + ".\n"
                + """
                # broader is the business domain; module is the business area. definition is the role
                # definition and the example of use joined, which is what BIAN states about the domain's
                # purpose. A domain BIAN states no role definition for is not carried.
                #
                # Source: BIAN's own published artefacts, one specification file per service domain, at
                """
                + "#   " + source + ",\n"
                + "#   pinned by the SHA-256 ContentDigest states over the specification set:\n"
                + "#   " + digest + ".\n"
                + "# Licence: Apache-2.0, stated in the publisher's own LICENSE file at that revision.\n"
                + "# Generated by BianServiceDomainsExtraction: " + count + " service domains.\n";
    }
}
