package io.github.fiftieshousewife.bi.lexicon.extraction;

import java.util.List;

import io.github.fiftieshousewife.bi.lexicon.SkosConcept;

/**
 * Renders CSO's topics as the TSV the lexicon bundles: a provenance header naming the archive the ontology
 * was read from and the digest that pins it, then the topics in the shape every taxonomy here is normalised
 * to.
 */
public class CsoTopicsTsv {

    private static final String JOINED = " | ";

    private final SkosTsv rows = new SkosTsv();

    public String render(final List<SkosConcept> concepts, final String source, final String digest) {
        return header(concepts, source, digest) + rows.render(concepts);
    }

    private static String header(final List<SkosConcept> concepts, final String source,
                                 final String digest) {
        final long withParent = concepts.stream().filter(topic -> !topic.broader().isEmpty()).count();
        final long withSeveral = concepts.stream().filter(topic -> topic.broader().contains(JOINED)).count();
        final int mostParents = concepts.stream()
                .mapToInt(topic -> topic.broader().split("\\Q" + JOINED + "\\E", -1).length)
                .max().orElse(0);
        return """
                # The Computer Science Ontology as a term taxonomy: the topics computer science research is
                # indexed by, each with the label CSO states for it and the equivalent labels it states beside
                # it. CSO states NO definition for any topic, so this is matched against declared names like
                # OLiA and FIBO and cannot be read as a functional taxonomy — there is no prose to compare a
                # scope against.
                #
                """
                + "# Columns: " + SkosTsv.COLUMNS + ".\n"
                + "# definition is empty for every row because CSO publishes none.\n"
                + "#\n"
                + "# CSO is a POLY-HIERARCHY: " + withSeveral + " of its " + withParent + " topics with a "
                + "parent are stated beneath more\n"
                + "# than one, up to " + mostParents + ". Every parent is carried, joined with the separator "
                + "SkosConcept states\n"
                + "# for a repeated property, and SkosConcept.broaderConcepts reads them back. Nothing is "
                + "dropped.\n"
                + "#\n"
                + "# Source: " + source + " (the download states\n"
                + "#   no revision, so the archive is the citation, pinned by the SHA-256 ContentDigest "
                + "states\n"
                + "#   over CSO.3.5.csv: " + digest + ").\n"
                + """
                # Licence: Creative Commons Attribution 4.0 International (CC BY 4.0) — "you can freely copy,
                #   share, adapt, and build upon the data for any purpose, including commercial use, as long as
                #   you give appropriate credit to the original creators". Credit: the Computer Science
                #   Ontology, Knowledge Media Institute, The Open University, and NOTICE.md carries it.
                #   The downloaded archive itself states no licence and carries no licence file; these terms
                #   were supplied by the maintainer of this repository rather than read from the archive.
                """
                + "# Generated by CsoTopicsExtraction: " + concepts.size() + " topics.\n";
    }
}
