package io.github.fiftieshousewife.bi.lexicon.extraction;

import java.util.List;

import io.github.fiftieshousewife.bi.lexicon.SkosConcept;

/**
 * Renders CWE's weaknesses as the TSV the lexicon bundles: a provenance header naming the revision and the
 * blob id that pin the one catalog file, and the licence MITRE states, then the concepts in the shape
 * every taxonomy here is normalised to.
 */
public class CweTermsTsv {

    private final SkosTsv rows = new SkosTsv();

    public String render(final List<SkosConcept> concepts, final String source, final String blob) {
        return header(concepts.size(), source, blob) + rows.render(concepts);
    }

    private static String header(final int count, final String source, final String blob) {
        return """
                # The Common Weakness Enumeration, as the terms a program working in security actually
                # writes. A weakness's name is a phrase — improper access control, integer overflow, use
                # after free — and a phrase is what a repository outside the domain does not hit by
                # accident. Each concept is the weakness's own permalink, so a match cites MITRE's page
                # for it.
                #
                """
                + "# Columns: " + SkosTsv.COLUMNS + ".\n"
                + """
                # prefLabel is the weakness's own name. broader is its ChildOf relation in the research
                # view — view 1000, CWE's one hierarchical statement of what is a kind of what — under the
                # parent's own name, joined with " | " where more than one parent is stated. kind is the
                # abstraction level MITRE states: Pillar, Class, Base, Variant or Compound. altLabel pools
                # the publisher's alternate terms. definition is the weakness's own description with its
                # line breaks collapsed. NOT CARRIED, and said outright: categories and views — a category
                # is a grouping a view draws for navigation, not a weakness.
                #
                # Source: the CWE 4.13 catalog XML as the OWASP cwe-sdk-javascript repository vendors it,
                """
                + "#   at " + source + ",\n"
                + "#   pinned by the blob id that revision holds:\n"
                + "#   " + blob + ".\n"
                + """
                # Licence: CWE is copyright The MITRE Corporation, and the CWE Terms of Use at
                #   https://cwe.mitre.org/about/termsofuse.html state that CWE is free to use by any
                #   organization or individual for any research, development, and/or commercial purposes,
                #   under a non-exclusive, royalty-free licence, on condition that MITRE's copyright
                #   designation and the licence are reproduced in any copy — which this header and
                #   NOTICE.md carry. The archive itself states no terms; the terms were read from MITRE's
                #   own page, and this header records that.
                """
                + "# Generated by CweTermsExtraction: " + count + " weaknesses.\n";
    }
}
