package io.github.fiftieshousewife.bi.lexicon.extraction;

import java.util.List;

import io.github.fiftieshousewife.bi.lexicon.SkosConcept;

/**
 * Renders FIX Orchestra's named things as the TSV the lexicon bundles: a provenance header naming the
 * revision and the blob id that pin the one Orchestra file, then the concepts in the shape every taxonomy
 * here is normalised to.
 */
public class FixTermsTsv {

    private final SkosTsv rows = new SkosTsv();

    public String render(final List<SkosConcept> concepts, final String source, final String blob) {
        return header(concepts.size(), source, blob) + rows.render(concepts);
    }

    private static String header(final int count, final String source, final String blob) {
        return """
                # The FIX protocol as the terms an electronic-trading system writes, read from FIX
                # Orchestra, the FIX Trading Community's machine-readable statement of FIX Latest. A FIX
                # engine declares these names directly — quickfixj states a class per field — and most are
                # phrases of more than one word, which is why the vocabulary is worth matching: a phrase is
                # what a repository outside the domain does not hit by accident.
                #
                """
                + "# Columns: " + SkosTsv.COLUMNS + ".\n"
                + """
                # kind is what Orchestra states each name as: the five sections, the categories each
                # section holds, the messages, components and repeating groups each category holds, and
                # the fields. broader is the stated section or category, and module is the section that
                # category sits in. A field states no category of its own: Orchestra places it through the
                # messages, components and groups that name it, so a field sits under the deepest concept
                # all of them sit under — their one category, or the section several categories share, and
                # nothing where they share nothing.
                # altLabel is the publisher's own abbreviated name where it states one; definition joins
                # the stated documentations in the publisher's order. NOT CARRIED, and said outright:
                # datatypes and code sets — a datatype is a value format and a code set an enumeration of
                # values, and neither is a subject a declared name can be about.
                #
                # Source: OrchestraFIXLatest.xml in the FIX Trading Community's own orchestrations
                """
                + "#   repository, at " + source + ",\n"
                + "#   pinned by the blob id that revision holds:\n"
                + "#   " + blob + ".\n"
                + "# Licence: Apache-2.0, stated in the publisher's own LICENSE file at that revision.\n"
                + "# Generated by FixTermsExtraction: " + count + " concepts.\n";
    }
}
