package io.github.fiftieshousewife.bi.lexicon.extraction;

import java.util.List;

import io.github.fiftieshousewife.bi.lexicon.SkosConcept;

/**
 * Renders FpML's complex types as the TSV the lexicon bundles: a provenance header naming the revision the
 * schemas were read at and the digest that pins the schema set, then the concepts in the shape every
 * taxonomy here is normalised to.
 */
public class FpmlTermsTsv {

    private final SkosTsv rows = new SkosTsv();

    public String render(final List<SkosConcept> concepts, final String source, final String digest) {
        return header(concepts.size(), source, digest) + rows.render(concepts);
    }

    private static String header(final int count, final String source, final String digest) {
        return """
                # The Financial products Markup Language, as the terms a program handling derivatives
                # trades actually writes. FpML's complex types are already identifiers — Swap, CapFloor,
                # CalculationPeriodDates — and most are phrases of more than one word, which is why the
                # vocabulary is worth matching: a phrase is what a repository outside the domain does not
                # hit by accident.
                #
                """
                + "# Columns: " + SkosTsv.COLUMNS + ".\n"
                + """
                # prefLabel is the complex type's own name. broader is its xsd:extension base, dropped where
                # the base carries a namespace prefix — such a base is XML Schema's, not FpML's — and
                # where it names a type this file carries no complex type for, as Scheme and
                # NonEmptyScheme are simple types: a roll-up must not climb to a concept nothing here
                # can answer for. definition is the type's
                # own xsd:documentation with its line breaks collapsed. module is the product area in the
                # schema file's own name: ird, cd, fx, eqd. NOT CARRIED, and said outright: simple types,
                # which are format constraints rather than subjects, and global elements, each of which
                # restates a complex type under a lowercased name.
                #
                # Which schemas: the FpML 5.11 confirmation view, which is the fullest statement of the
                # products the standard covers — the other views restate its types with fields removed.
                #
                # Source: the FpML 5.11 confirmation schemas as the HandCoded toolkit repository vendors
                """
                + "#   them, at " + source + ",\n"
                + "#   pinned by the SHA-256 ContentDigest states over the schema set:\n"
                + "#   " + digest + ".\n"
                + """
                # Licence: the FpML Public License, stated in each schema file's own header. The Licensor of
                #   the FpML Specifications is the International Swaps and Derivatives Association, Inc.
                #   (ISDA); the licence is at https://www.fpml.org/the_standard/fpml-public-license/ and
                #   grants use, reproduction, modification and distribution of the specifications or
                #   portions of them, with this notice carried on a copy distributed outside software.
                """
                + "# Generated by FpmlTermsExtraction: " + count + " complex types.\n";
    }
}
