package io.github.fiftieshousewife.bi.lexicon.extraction;

import java.util.List;

import io.github.fiftieshousewife.bi.lexicon.SkosConcept;

/**
 * Renders the IANA media type registry as the TSV the lexicon bundles: a provenance header naming the
 * registry files this was read from and the digest that pins them, then the types in the shape every
 * taxonomy here is normalised to.
 */
public class MediaTypesTsv {

    public String render(final List<SkosConcept> concepts, final String source, final String digest) {
        return header(concepts, source, digest) + new SkosTsv().render(concepts);
    }

    private static String header(final List<SkosConcept> concepts, final String source,
                                 final String digest) {
        return """
                # The IANA media type registry: every registered type, carried byte for byte as the registry
                # states it. A string literal equal to a row's identifier is the publisher's own identifier
                # written into a repository, which is a citation no English word can make; nothing here is an
                # English label, so this is never matched against a declared name and never placed as prose.
                #
                """
                + "# Columns: " + SkosTsv.COLUMNS + ".\n"
                + "# concept and prefLabel are the registered template, byte for byte. broader and module "
                + "name the\n"
                + "# registry the type is filed under. definition is empty for every row because the "
                + "registry\n"
                + "# publishes none. note carries the registry's reference, and its own deprecation "
                + "statement where\n"
                + "# it makes one — a deprecated identifier is still the registry's identifier, so the row "
                + "stays.\n"
                + "#\n"
                + "# Source: " + source + "\n"
                + "#   (the registry states no revision, so the file set is the citation, pinned by the "
                + "SHA-256\n"
                + "#   ContentDigest states over the ten CSVs: " + digest + ").\n"
                + """
                # Licence: CC0 1.0 (https://www.iana.org/help/licensing-terms — "IANA and IETF intend that
                #   the Protocol Registries may be freely used by any party for any purpose", with both
                #   organisations' rights "subject to the Creative Commons CC0 1.0 dedication").
                """
                + "# Generated by MediaTypeExtraction: " + concepts.size() + " media types.\n";
    }
}
