package io.github.fiftieshousewife.bi.lexicon.extraction;

import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Renders the counts OpenAlex sizes each topic by, as the TSV the lexicon bundles beside the taxonomy.
 *
 * <p>It is a second file rather than a ninth column because SKOS states no property for how much of a
 * corpus sits under a concept. The eight columns hold statements of meaning and position, all of them text,
 * and a count is neither — across the 25,550 rows of the eight bundled files not one carries a number.
 *
 * <p>The two files cannot drift apart because one extraction pass writes both from one snapshot and both
 * headers name the digest that pins it, which {@code OpenAlexTopicSizesTest} asserts.
 */
public class OpenAlexTopicSizesTsv {

    static final String COLUMNS = "concept, worksCount, citedByCount";

    private static final String COLUMN = "\t";

    private static final String ROW = "\n";

    /** Only a topic is counted: OpenAlex counts no subfield, field or domain, so none is written. */
    public String render(final List<OpenAlexTopic> topics, final String source, final String digest) {
        return header(topics.size(), source, digest) + topics.stream()
                .sorted(Comparator.comparing(OpenAlexTopic::concept))
                .map(OpenAlexTopicSizesTsv::row)
                .collect(Collectors.joining());
    }

    private static String row(final OpenAlexTopic topic) {
        return topic.concept() + COLUMN + topic.worksCount() + COLUMN + topic.citedByCount() + ROW;
    }

    private static String header(final int count, final String source, final String digest) {
        return """
                # How much of the literature OpenAlex places under each of its topics: the works it counts
                # under the topic and the citations those works received. This is the publisher's own
                # measure of how broad a topic is, and the spread is wide enough that a reading treating
                # every topic as the same size is stating something OpenAlex did not — the largest topic
                # holds several per cent of every work counted and the smallest a few ten-thousandths of
                # one per cent.
                #
                # It is bundled beside openalex-topics.tsv rather than inside it because the eight columns
                # of that file are SKOS's own properties, all of them text, and SKOS states no property for
                # the size of a concept's corpus. The two files are written by one pass over one snapshot
                # and both name the digest below, so a file regenerated against a different snapshot cannot
                # sit beside one that was not.
                #
                # Columns:\s""" + COLUMNS + """
                . One row per topic; OpenAlex counts no subfield, field or domain,
                # so those are absent rather than zero.
                #
                # Source:\s""" + source + """
                ,
                #   pinned by the SHA-256 ContentDigest states over the manifest and the parts it names:
                #  \s""" + digest + """
                .
                # Licence: CC0 1.0 Universal. OpenAlex places its data in the public domain and asks to be
                #   cited rather than requiring it (https://docs.openalex.org/additional-help/faq).
                # Generated by OpenAlexTopicsExtraction:\s""" + count + " topics.\n";
    }
}
