package io.github.fiftieshousewife.bi.lexicon.extraction;

import java.util.List;

import io.github.fiftieshousewife.bi.lexicon.SkosConcept;

/**
 * Renders OpenAlex's topics as the TSV the lexicon bundles: a provenance header naming the snapshot the
 * records were read from and the digest that pins it, then the concepts in the shape every taxonomy here is
 * normalised to.
 */
public class OpenAlexTopicsTsv {

    private final SkosTsv rows = new SkosTsv();

    public String render(final List<SkosConcept> concepts, final String source, final String digest) {
        return header(concepts.size(), source, digest) + rows.render(concepts);
    }

    private static String header(final int count, final String source, final String digest) {
        return """
                # OpenAlex's topics as a subject taxonomy of research: four domains, the fields inside them,
                # the subfields inside those and the topics inside those, each topic carrying the prose
                # OpenAlex states its subject matter in. Like every subject taxonomy here it is a
                # distribution to compare against and not a vocabulary to match — nobody writes T11347 in
                # code, and nobody writes Neural Networks Stability and Synchronization either. What a scope
                # is compared on is the definition.
                #
                # Columns:\s""" + SkosTsv.COLUMNS + """
                .
                # broader is the subfield a topic is stated in, the field a subfield is stated in, the domain
                # a field is stated in, and empty for a domain; module is the domain a concept rolls up to.
                # definition is the description and the keywords, which are both OpenAlex's statement of what
                # the topic covers, and it is empty above topic level because OpenAlex describes no subfield,
                # field or domain. note is the Wikipedia article OpenAlex links the topic to, which
                # identifies it in a scheme outside this one. altLabel is empty: OpenAlex states no second
                # label for anything.
                #
                # Source:\s""" + source + """
                ,
                #   pinned by the SHA-256 ContentDigest states over the manifest and the parts it names:
                #  \s""" + digest + """
                .
                # Licence: CC0 1.0 Universal. OpenAlex places its data in the public domain and asks to be
                #   cited rather than requiring it (https://docs.openalex.org/additional-help/faq).
                # Generated by OpenAlexTopicsExtraction:\s""" + count + " concepts.\n";
    }
}
