package io.github.fiftieshousewife.bi.lexicon.extraction;

import java.util.Collection;
import java.util.Comparator;
import java.util.List;

/**
 * Renders the catalogue as the TSV the lexicon bundles: a provenance header naming the engine and the
 * version the entries were read from, then one sorted row per named function carrying a description.
 * An entry with no description states nothing and is left out.
 */
public class SqlFunctionTsv {

    public String render(final Collection<SqlFunction> functions, final String engineVersion) {
        final List<SqlFunction> rows = functions.stream()
                .filter(function -> !function.description().isBlank())
                .distinct()
                .sorted(Comparator.comparing(SqlFunction::name).thenComparing(SqlFunction::description))
                .toList();
        final StringBuilder text = new StringBuilder(header(rows.size(), engineVersion));
        rows.forEach(row -> text.append(row.name()).append('\t')
                .append(row.description()).append('\n'));
        return text.toString();
    }

    private static String header(final int count, final String engineVersion) {
        return """
                # The query language's own function catalogue: a function name and the description the
                # engine publishes for it. A schema token equal to a function's name is a fact about the
                # standard this tool executes rather than an observation of any corpus, and the entry's
                # own description is what states the words the name stands for — abs is published as
                # "Absolute value", which is the citation, not a guess about it.
                #
                # Source: DuckDB's duckdb_functions() catalogue, read from the embedded engine at
                #   version\s""" + engineVersion + """
                ; scalar and aggregate functions only.
                # Licence: DuckDB is distributed under the MIT licence
                #   (https://github.com/duckdb/duckdb/blob/main/LICENSE). A function's name and the
                #   description of what it computes are statements of the standard the tool runs.
                # Generated by SqlFunctionExtraction:\s""" + count + " functions.\n";
    }
}
