package io.github.fiftieshousewife.codesemantics.lexicon.extraction;

import java.util.List;

import io.github.fiftieshousewife.codesemantics.lexicon.SkosConcept;

/**
 * Renders the Conventional Commits tokens as the TSV the lexicon bundles: a provenance header naming the
 * two pinned statements the rows were read from, then one row per token in the shape every vocabulary
 * here is normalised to.
 */
public class ConventionalCommitTypesTsv {

    private final SkosTsv rows = new SkosTsv();

    public String render(final List<SkosConcept> concepts, final String specification,
                         final String convention) {
        return header(concepts.size(), specification, convention) + rows.render(concepts);
    }

    private static String header(final int count, final String specification, final String convention) {
        return """
                # Conventional Commits 1.0.0: the commit types and the breaking-change footer the
                # specification states for a commit message's first line. A commit prefixed fix: writes
                # the specification's word, not the author's, so a statement parsed under this grammar
                # can be cited to the standard the way a language keyword is cited to its specification.
                #
                """
                + "# Columns: " + SkosTsv.COLUMNS + ".\n"
                + """
                # concept and prefLabel are the token as the specification writes it. kind is type or
                # footer. module is specification for the tokens the specification defines itself — feat,
                # fix and the BREAKING CHANGE footer — and angular-convention for the types it names as
                # recommended by @commitlint/config-conventional, whose definitions are the Angular
                # convention's own at the revision the specification's link pins. chore is named there
                # and defined by neither source, so its definition is empty. altLabel, broader and note
                # are empty: neither source states another label, a hierarchy or a remark.
                #
                # Name: Conventional Commits 1.0.0
                # Short name: Conventional Commits
                # Publisher: the Conventional Commits contributors
                # Published at: https://www.conventionalcommits.org/en/v1.0.0/
                # Kind: identifiers
                # Description: Conventional Commits: the change types a commit message's first line states.
                # Subject: change description
                """
                + "# Source: " + specification + ";\n"
                + "#   type definitions from " + convention + ",\n"
                + "#   the revision the specification's own link pins.\n"
                + """
                # Licence: MIT for both sources — the specification site
                #   (https://github.com/conventional-commits/conventionalcommits.org/blob/master/LICENSE)
                #   and the Angular repository (https://github.com/angular/angular/blob/main/LICENSE).
                """
                + "# Generated by ConventionalCommitTypesExtraction: " + count + " tokens.\n";
    }
}
