package io.github.fiftieshousewife.codesemantics.lexicon.extraction;

/**
 * Renders the NIST CSRC glossary as the TSV the lexicon bundles: a provenance header naming the export
 * this was read from and the digest that pins it, then the terms in the shape every taxonomy here is
 * normalised to.
 */
public class CsrcGlossaryTsv {

    private final SkosTsv rows = new SkosTsv();

    public String render(final CsrcConcepts.Read read, final String source, final String digest) {
        return header(read, source, digest) + rows.render(read.concepts());
    }

    private static String header(final CsrcConcepts.Read read, final String source, final String digest) {
        return """
                # The NIST Computer Security Resource Center glossary: the terms NIST's own information
                # security publications define, with the abbreviations and synonyms the glossary states
                # beside each. A declared name equal to a term or to a stated abbreviation is the
                # publisher's own word for a security concept, and each concept is the glossary's permalink
                # for it, so a match cites NIST's record.
                #
                """
                + "# Columns: " + SkosTsv.COLUMNS + ".\n"
                + """
                # concept is the glossary's permalink for the term. prefLabel is the term as the glossary
                # writes it, as the text its HTML renders as. altLabel pools the stated abbreviations and
                # synonyms. definition joins the stated definitions in the order the glossary writes them.
                # note carries the glossary's own note on the term and the terms its see-also statements
                # point at. broader and module are blank on every row: the glossary states no hierarchy,
                # and the blank is the publisher's statement. A statement carrying this file's statement
                # separator cannot be written into its shape and is set aside rather than rewritten; the
                # count below says how many were.
                #
                # Name: NIST CSRC glossary
                # Short name: CSRC
                # Publisher: the National Institute of Standards and Technology
                # Published at: https://csrc.nist.gov/glossary
                # Kind: terms
                # Description: CSRC: the terms NIST's information security publications define.
                # Subject: information security
                """
                + "# Source: " + source + ",\n"
                + """
                #   rebuilt continuously with no stated version, so it is pinned by this library's own
                #   digest over it — a weaker claim than a publisher's revision, and stated as such:
                """
                + "#   " + digest + ".\n"
                + """
                # Licence: public domain in the United States as a work of the US federal government
                #   (17 U.S.C. 105); CSRC states that except where otherwise noted, content on the site is
                #   in the public domain. The glossary's own comment field asks that NISTIR 7298 Rev. 3 be
                #   cited as the description of its design, and NOTICE.md carries that citation.
                """
                + "# Generated by CsrcGlossaryExtraction: " + read.concepts().size()
                + " terms; statements set aside: " + read.statementsSetAside().size() + ".\n";
    }
}
