package io.github.fiftieshousewife.codesemantics.lexicon.extraction;

import java.util.List;
import java.util.Locale;

import io.github.fiftieshousewife.codesemantics.lexicon.SkosConcept;

/**
 * Renders one fork of ethereum/execution-specs as the TSV the lexicon bundles: a provenance header naming
 * the pinned commit, the fork the specification schedules last and the digest over its modules, and the
 * CC0 dedication the repository states, then the concepts in the shape every taxonomy here is normalised
 * to.
 */
public class ExecutionSpecTermsTsv {

    private final SkosTsv rows = new SkosTsv();

    public String render(final List<SkosConcept> concepts, final String fork, final String source,
                         final String digest) {
        return header(concepts.size(), fork, source, digest) + rows.render(concepts);
    }

    private static String header(final int count, final String fork, final String source,
                                 final String digest) {
        return """
                # The Ethereum execution-layer specification, as the terms a program working on a
                # distributed ledger actually writes. The specification is executable Python, and its
                # declared nouns are its vocabulary: base_fee_per_gas, SetCodeTransaction, excess_blob_gas,
                # the EVM's own opcode mnemonics. Most read as phrases of more than one word, which is what
                # a repository outside the domain does not hit by accident. Each concept is the dotted
                # reference path the specification's own docstrings cite.
                #
                """
                + "# Columns: " + SkosTsv.COLUMNS + ".\n"
                + """
                # prefLabel is the declared name as the specification writes it. kind is what the module
                # states it as: class, field or constant. broader is the class holding a field or
                # constant, blank at module level. module is the file's dotted path inside the fork.
                # definition is the first paragraph of the declaration's own docstring. NOT CARRIED, and
                # said outright: functions and methods — the specification's functions are the procedures
                # that manipulate its nouns, written in general words (account_exists, less_than) that
                # repositories outside the field declare for their own reasons, and its classes' few
                # methods are machinery; names beginning with an underscore, the language's own convention
                # for a private name; and every other fork package, because each fork restates the whole
                # specification and one statement of it is the vocabulary.
                #
                """
                + String.format(Locale.ROOT, "# Name: Ethereum execution specs, %s fork%n", fork)
                + """
                # Short name: EELS
                # Publisher: the Ethereum project
                # Published at: https://github.com/ethereum/execution-specs
                # Kind: terms
                # Description: The Ethereum execution-layer specification: the names one fork of the executable spec declares.
                # Subject: distributed ledger
                """
                + String.format(Locale.ROOT,
                        "# Source: the fork the specification schedules last, %s, every module of it at%n", fork)
                + "#   " + source + ",\n"
                + """
                #   pinned by a digest over those modules' own blob ids:
                """
                + "#   " + digest + ".\n"
                + """
                # Licence: LICENSE.md states CC0 1.0 Universal — the authors waive copyright to the extent
                #   possible under law. No attribution is required; NOTICE.md records the source.
                """
                + "# Generated by ExecutionSpecTermsExtraction: " + count + " declarations.\n";
    }
}
