package io.github.fiftieshousewife.codesemantics.lexicon.extraction;

import java.util.List;

import io.github.fiftieshousewife.codesemantics.lexicon.SkosConcept;

/**
 * Renders the IANA JOSE registries as the TSV the lexicon bundles: a provenance header naming the
 * registry files this was read from and the digest that pins them, then the registrations in the shape
 * every taxonomy here is normalised to.
 */
public class JoseTermsTsv {

    private final SkosTsv rows = new SkosTsv();

    public String render(final List<SkosConcept> concepts, final String source, final String digest) {
        return header(concepts.size(), source, digest) + rows.render(concepts);
    }

    private static String header(final int count, final String source, final String digest) {
        return """
                # The IANA JSON Object Signing and Encryption (JOSE) registries: every registered
                # algorithm, header parameter, key parameter, key type, curve, key use and key operation,
                # under the name the registry states for it. The registered value is the string a JOSE
                # implementation writes — HS256, kty, sig, x5c — and the description beside it is the
                # publisher's English name for what it does.
                #
                """
                + "# Columns: " + SkosTsv.COLUMNS + ".\n"
                + """
                # concept scopes the registered value by its registry, because IANA states no per-row
                # permalink and registers one value in more than one place. prefLabel is the registered
                # value, byte for byte. altLabel joins the stated descriptions of every registration of
                # that value. broader and module name the registry. note carries the stated references.
                # definition is empty for every row because the registries publish none. NOT CARRIED, and
                # said outright: the usage locations, implementation requirements and change controllers —
                # they state conformance, not what a row names.
                #
                # Name: IANA JOSE registries
                # Short name: JOSE
                # Publisher: the Internet Assigned Numbers Authority
                # Published at: https://www.iana.org/assignments/jose/
                # Kind: terms
                # Description: JOSE: the names IANA registers for JSON signing and encryption.
                # Subject: JSON object signing and encryption
                """
                + "# Source: " + source + "\n"
                + "#   (the registries state no revision, so the file set is the citation, pinned by the "
                + "SHA-256\n"
                + "#   ContentDigest states over the nine CSVs: " + digest + ").\n"
                + """
                # Licence: CC0 1.0 (https://www.iana.org/help/licensing-terms — "IANA and IETF intend that
                #   the Protocol Registries may be freely used by any party for any purpose", with both
                #   organisations' rights "subject to the Creative Commons CC0 1.0 dedication").
                """
                + "# Generated by JoseTermsExtraction: " + count + " registered values.\n";
    }
}
