package io.github.fiftieshousewife.codesemantics.lexicon.extraction;

import java.util.List;

import io.github.fiftieshousewife.codesemantics.lexicon.SkosConcept;

/**
 * Renders PRONOM's file formats as the TSV the lexicon bundles: a provenance header naming the signature
 * file release and the digest that pin it, and the licence The National Archives states, then the
 * concepts in the shape every taxonomy here is normalised to.
 */
public class PronomFormatsTsv {

    private final SkosTsv rows = new SkosTsv();

    public String render(final List<SkosConcept> concepts, final String source, final String digest) {
        return header(concepts.size(), source, digest) + rows.render(concepts);
    }

    private static String header(final int count, final String source, final String digest) {
        return """
                # PRONOM, The National Archives' registry of file formats, as the terms a program working
                # with documents actually writes. A format's name is a phrase — Portable Document Format,
                # Extensible Hypertext Markup Language, Scalable Vector Graphics — and the registry states
                # each format's extensions and media types beside it, which are the short names a parser or
                # a test fixture declares. Each concept is the format's PUID at the registry's own
                # permalink, so a match cites The National Archives' record for it.
                #
                """
                + "# Columns: " + SkosTsv.COLUMNS + ".\n"
                + """
                # prefLabel is the format's own name. altLabel pools the stated extensions and media
                # types. note carries the stated version, because PRONOM publishes one record per version
                # of a format. broader and definition are blank on every row: the signature file states no
                # hierarchy and no prose, and the blank is the publisher's statement. NOT CARRIED, and
                # said outright: the container signature file — it maps container signatures to PUIDs this
                # file already names, and states no format row of its own.
                #
                # Name: PRONOM signature file V125
                # Short name: PRONOM
                # Publisher: The National Archives
                # Published at: https://www.nationalarchives.gov.uk/pronom/
                # Kind: terms
                # Description: PRONOM: the names The National Archives states for file formats.
                # Subject: file formats
                """
                + "# Source: " + source + ",\n"
                + """
                #   a numbered release the publisher does not state a content address for, so it is pinned
                #   by this library's own digest over it — a weaker claim than a publisher's revision, and
                #   stated as such:
                """
                + "#   " + digest + ".\n"
                + """
                # Licence: the site footer states Open Government Licence v3.0, which permits copying,
                #   publishing and adapting the information with attribution. The attribution statement it
                #   requires — contains public sector information licensed under the Open Government
                #   Licence v3.0 — is carried here and in NOTICE.md.
                """
                + "# Generated by PronomFormatsExtraction: " + count + " formats.\n";
    }
}
