package io.github.fiftieshousewife.codesemantics.lexicon.extraction;

import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;

/**
 * Renders the reduced eXtended WordNet Domains as the TSV the lexicon bundles: a provenance header, then
 * one row per sense key — the key, its synset's leading domain, and the weight the propagation gives it.
 */
final class XwndDomainsTsv {

    private static final String COLUMN = "\t";
    private static final String ROW = "\n";

    String render(final List<XwndConcepts.Leading> keyed, final String sourceUrl,
                  final String archiveSha256, final String indexUrl, final String indexSha256) {
        return header(keyed.size(), sourceUrl, archiveSha256, indexUrl, indexSha256) + rows(keyed);
    }

    private static String header(final int rows, final String sourceUrl, final String archiveSha256,
                                 final String indexUrl, final String indexSha256) {
        return """
                # eXtended WordNet Domains, reduced to one domain per synset and keyed by sense key: for
                # each WordNet 3.0 synset, the domain whose propagation vector weighs it highest, carried
                # onto every sense key the synset holds. The maximum is the reduction the resource's own
                # evaluation uses and the one-domain-per-synset shape its successors publish; a tie breaks
                # on the domain's name, so two runs write identical bytes.
                #
                # Columns: senseKey, domain, weight.
                #   senseKey  WordNet's own version-stable sense identifier, from WordNet 3.0's index.sense.
                #             It is what lets these labels join the bundled WordNet 3.1 database: the 3.0
                #             synset offsets the distribution is keyed by survive in almost no case, and the
                #             sense keys survive in almost every one.
                #   domain    the leading domain of the synset across all 170 propagation vectors.
                #   weight    that domain's propagation weight for the synset. Each domain's vector sums to
                #             one over the 117,536 synsets, so weights compare across domains.
                #
                """
                + "# Name: eXtended WordNet Domains\n"
                + "# Publisher: the IXA group, University of the Basque Country\n"
                + "# Kind: words\n"
                + "# Source: " + sourceUrl + ", accepted only at\n"
                + "#   sha256 " + archiveSha256 + ";\n"
                + "#   joined through index.sense of " + indexUrl + ",\n"
                + "#   accepted only at sha256 " + indexSha256 + ".\n"
                + "#   Gonzalez-Agirre, A., Castillo, M. and Rigau, G.: A proposal for improving WordNet\n"
                + "#   Domains. LREC 2012. https://adimen.ehu.eus/web/XWND\n"
                + "# Licence: Creative Commons Attribution 3.0 Unported (CC BY 3.0). Attribution: eXtended\n"
                + "#   WordNet Domains, IXA group, University of the Basque Country (UPV/EHU). WordNet 3.0\n"
                + "#   index.sense under the WordNet licence, Princeton University.\n"
                + "#\n"
                + "# Generated by XwndDomainsExtraction: " + rows + " rows.\n";
    }

    private static String rows(final List<XwndConcepts.Leading> keyed) {
        return keyed.stream()
                .sorted(Comparator.comparing(XwndConcepts.Leading::senseKey))
                .map(leading -> String.join(COLUMN, leading.senseKey(), leading.domain(),
                        String.format(Locale.ROOT, "%.6e", leading.weight())))
                .collect(Collectors.joining(ROW, "", ROW));
    }
}
