package io.github.fiftieshousewife.codesemantics.corpus;

import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Renders a pooled corpus of runs as the TSV the reference bundles: the same provenance header the word
 * table carries, saying instead which index the runs were merged under, then one row per run.
 */
public final class PooledRunsTsv {

    public static final String COLUMNS = "run\toccurrences\tshare\terror";

    private static final String COLUMN = "\t";

    public String render(final CorpusWords corpus, final DrawnManifest draw, final CorpusPooling pooling) {
        return header(corpus, draw, pooling) + PooledRows.of(corpus, pooling);
    }

    private static String header(final CorpusWords corpus, final DrawnManifest draw,
                                 final CorpusPooling pooling) {
        return """
                # The reference corpus, over runs: how densely working Java writes each run of words some
                # publisher states as one entry, pooled over the repositories a seeded draw took. It is a
                # denominator and nothing else. No row states a subject, nothing here is scored, and a run
                # absent from it has a share of zero.
                #
                """
                + "# Columns: " + COLUMNS.replace(COLUMN, ", ") + ".\n"
                + """
                #   run          the words as the identifier splitter produced them from a name a repository
                #                declared, joined by the character the resources key a collocation with.
                #   occurrences  how many times the pooled repositories declared it, summed over all of them
                #                and independent of the weighting below.
                #   share        what a reading is read against. It sums to one over this table.
                #   error        the standard error of that share under this table's own weighting - for the
                #                mean of shares, the between-repository standard error of the mean; for
                #                pooled occurrences, the binomial standard error of the proportion. A verdict
                #                whose margin sits inside it has not been shown to stand above chance.
                #
                # WHAT WAS READ. Every tree was read by the path this library reads itself with: the Java
                # source sets, the documentation and the build modules beside them, parsed, split by
                # IdentifierWords, and taken at the stage that keeps the names a repository declared and
                # leaves out the sentences it wrote about them. Both sides of a comparison are therefore made
                # the same way, which is the only thing that makes a share here comparable to a share there.
                #
                # WHICH RUNS COULD BE COUNTED. Two adjacent words are merged into one run only where a
                # publisher states that run, so the index decides what this table can see. This table is
                # pooled under EveryPublishedRun - the two topical dictionaries' collocations and the seven
                # bundled term vocabularies' multi-word concept labels together - because it is asked how
                # often working Java writes a vocabulary's own terms, and a run no index states would read as
                # absent from the corpus whatever the corpus writes. The word table is pooled under the
                # dictionaries alone, which is the index a reading runs on. This one is read only where a
                # published term is judged against general Java, and by nothing in the word path.
                #
                # Each repository's shares are taken over its runs alone, so this table is a distribution
                # over runs and a run's rank in it is a rank among runs.
                #
                """
                + "# HOW IT IS WEIGHTED: " + pooling + " — " + pooling.weighs() + ".\n"
                + "#   One read writes a table per weighting — " + everyTable() + " — so they differ in\n"
                + "#   this line and in the share column alone.\n"
                + "#\n"
                + "# Name: the reference corpus, over runs\n"
                + "# Publisher: this library, from a seeded draw of public Java repositories\n"
                + "# Kind: frequencies\n"
                + "# Source: " + draw.name() + ", copied below, which states the frame, the predicate and\n"
                + "#   the seed. Every repository was cloned at the commit it pins.\n"
                + "# Licence: these counts are this project's measurement of publicly available source. Every\n"
                + "#   repository pooled states a licence GitHub recognises, named beside it below.\n"
                + "#\n"
                + "# Generated by CorpusRunPoolCommand.\n"
                + "# Repositories pooled: " + corpus.repositories()
                + ". Runs: " + corpus.words().size()
                + ". Occurrences: " + corpus.totalOccurrences() + ".\n"
                + "#\n"
                + CopiedManifest.of(draw);
    }

    private static String everyTable() {
        return Stream.of(CorpusPooling.values())
                .map(CorpusPooling::runFileName)
                .collect(Collectors.joining(", "));
    }
}
