package io.github.fiftieshousewife.codesemantics.corpus;

import java.util.Comparator;
import java.util.Locale;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import io.github.fiftieshousewife.codesemantics.clones.PinnedRepository;
import io.github.fiftieshousewife.codesemantics.engine.reading.WrittenWords;

/**
 * Renders the pooled corpus as the TSV the reference bundles: a provenance header carrying the manifest that
 * drew the repositories, then one row per word.
 */
public final class PooledVocabularyTsv {

    public static final String COLUMNS = "word\toccurrences\tshare";

    private static final String COLUMN = "\t";
    private static final String ROW = "\n";

    public String render(final WrittenWords pooled, final DrawnManifest draw) {
        return header(pooled, draw) + rows(pooled);
    }

    private static String header(final WrittenWords pooled, final DrawnManifest draw) {
        return """
                # The reference corpus: how densely working Java writes each word, pooled over the
                # repositories a seeded draw took. It is a denominator and nothing else. No row states a
                # subject, nothing here is scored, and a word absent from it has a share of zero.
                #
                """
                + "# Columns: " + COLUMNS.replace(COLUMN, ", ") + ".\n"
                + """
                #   word         as the identifier splitter produced it, from a name a repository declared.
                #   occurrences  how many times the pooled repositories declared it.
                #   share        occurrences divided by the total, stated for a reader of this file. A reader
                #                of the table derives the share from the count, so rounding here moves nothing.
                #
                # WHAT WAS READ. Every tree was read by the path this library reads itself with: the Java
                # source sets, the documentation and the build modules beside them, parsed, split by
                # IdentifierWords, and taken at the stage that keeps the names a repository declared and
                # leaves out the sentences it wrote about them. Both sides of a comparison are therefore made
                # the same way, which is the only thing that makes a share here comparable to a share there.
                #
                """
                + "# Source: " + draw.name() + ", copied below, which states the frame, the predicate and\n"
                + "#   the seed. Every repository was cloned at the commit it pins.\n"
                + "# Licence: these counts are this project's measurement of publicly available source. Every\n"
                + "#   repository pooled states a licence GitHub recognises, named beside it below.\n"
                + "#\n"
                + "# Generated by CorpusPoolCommand.\n"
                + "# Repositories pooled: " + draw.manifest().repositories().size()
                + ". Words: " + pooled.words().size()
                + ". Occurrences: " + pooled.totalOccurrences() + ".\n"
                + "#\n"
                + drawn(draw);
    }

    /** The manifest whole: the header it states, then the repositories it pins. */
    private static String drawn(final DrawnManifest draw) {
        return Stream.concat(draw.stated().stream(), draw.manifest().repositories().stream()
                        .map(PooledVocabularyTsv::pinned))
                .collect(Collectors.joining(ROW, "", ROW));
    }

    private static String pinned(final PinnedRepository repository) {
        return "# " + String.join(COLUMN, repository.name(), repository.origin(), repository.sha(),
                repository.licence());
    }

    private static String rows(final WrittenWords pooled) {
        final int total = pooled.totalOccurrences();
        if (total == 0) {
            throw new IllegalStateException("The corpus pooled no words at all, and an empty denominator "
                    + "demotes nothing — which is indistinguishable from a reference that found nothing to "
                    + "demote. Check that the clones are where the run was pointed.");
        }
        final Comparator<String> byOccurrences = Comparator.comparingInt(pooled::occurrencesOf);
        return pooled.words().stream()
                .sorted(byOccurrences.reversed().thenComparing(Comparator.naturalOrder()))
                .map(word -> row(word, pooled.occurrencesOf(word), total))
                .collect(Collectors.joining(ROW, "", ROW));
    }

    private static String row(final String word, final int occurrences, final int total) {
        return String.join(COLUMN, word, String.valueOf(occurrences),
                String.format(Locale.ROOT, "%.3e", (double) occurrences / total));
    }
}
