package io.github.fiftieshousewife.codesemantics.corpus;

import java.util.Comparator;
import java.util.Locale;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import io.github.fiftieshousewife.codesemantics.clones.PinnedRepository;

/**
 * Renders a pooled corpus as the TSV the reference bundles: a provenance header carrying the manifest that
 * drew the repositories and the weighting this table was pooled under, then one row per word.
 */
public final class PooledVocabularyTsv {

    public static final String COLUMNS = "word\toccurrences\tshare\terror";

    private static final String COLUMN = "\t";
    private static final String ROW = "\n";

    public String render(final CorpusWords corpus, final DrawnManifest draw, final CorpusPooling pooling) {
        return header(corpus, draw, pooling) + rows(corpus, pooling);
    }

    private static String header(final CorpusWords corpus, final DrawnManifest draw,
                                 final CorpusPooling pooling) {
        return """
                # The reference corpus: how densely working Java writes each word, pooled over the
                # repositories a seeded draw took. It is a denominator and nothing else. No row states a
                # subject, nothing here is scored, and a word absent from it has a share of zero.
                #
                """
                + "# Columns: " + COLUMNS.replace(COLUMN, ", ") + ".\n"
                + """
                #   word         as the identifier splitter produced it, from a name a repository declared.
                #   occurrences  how many times the pooled repositories declared it, summed over all of them
                #                and independent of the weighting below.
                #   share        what a reading is read against. It sums to one over this table.
                #   error        the standard error of that share under this table's own weighting - for the
                #                mean of shares, the between-repository standard error of the mean; for
                #                pooled occurrences, the binomial standard error of the proportion. A verdict
                #                whose margin sits inside it has not been shown to stand above chance.
                #
                # WHAT WAS READ. Every tree was read by the path this library reads itself with: the Java
                # source sets, the documentation and the build modules beside them, parsed, split by
                # IdentifierWords, and taken at the stage that keeps the names a repository declared and
                # leaves out the sentences it wrote about them. Both sides of a comparison are therefore made
                # the same way, which is the only thing that makes a share here comparable to a share there.
                #
                """
                + "# HOW IT IS WEIGHTED: " + pooling + " — " + pooling.weighs() + ".\n"
                + "#   One read writes a table per weighting — " + everyTable() + " — so they differ in\n"
                + "#   this line and in the share column alone.\n"
                + "#\n"
                + "# Source: " + draw.name() + ", copied below, which states the frame, the predicate and\n"
                + "#   the seed. Every repository was cloned at the commit it pins.\n"
                + "# Licence: these counts are this project's measurement of publicly available source. Every\n"
                + "#   repository pooled states a licence GitHub recognises, named beside it below.\n"
                + "#\n"
                + "# Generated by CorpusPoolCommand.\n"
                + "# Repositories pooled: " + corpus.repositories()
                + ". Words: " + corpus.words().size()
                + ". Occurrences: " + corpus.totalOccurrences() + ".\n"
                + "#\n"
                + drawn(draw);
    }

    private static String everyTable() {
        return Stream.of(CorpusPooling.values())
                .map(CorpusPooling::fileName)
                .collect(Collectors.joining(", "));
    }

    /** The manifest whole: the header it states, then the repositories it pins. */
    private static String drawn(final DrawnManifest draw) {
        return Stream.concat(draw.stated().stream(), draw.manifest().repositories().stream()
                        .map(PooledVocabularyTsv::pinned))
                .collect(Collectors.joining(ROW, "", ROW));
    }

    private static String pinned(final PinnedRepository repository) {
        return "# " + String.join(COLUMN, repository.name(), repository.origin(), repository.sha(),
                repository.licence());
    }

    private static String rows(final CorpusWords corpus, final CorpusPooling pooling) {
        if (corpus.totalOccurrences() == 0) {
            throw new IllegalStateException("The corpus pooled no words at all, and an empty denominator "
                    + "demotes nothing — which is indistinguishable from a reference that found nothing to "
                    + "demote. Check that the clones are where the run was pointed.");
        }
        final Comparator<String> byShare =
                Comparator.comparingDouble(word -> pooling.shareOf(word, corpus));
        return corpus.words().stream()
                .sorted(byShare.reversed().thenComparing(Comparator.naturalOrder()))
                .map(word -> row(word, corpus, pooling))
                .collect(Collectors.joining(ROW, "", ROW));
    }

    private static String row(final String word, final CorpusWords corpus, final CorpusPooling pooling) {
        return String.join(COLUMN, word, String.valueOf(corpus.occurrencesOf(word)),
                String.format(Locale.ROOT, "%.3e", pooling.shareOf(word, corpus)),
                String.format(Locale.ROOT, "%.3e", pooling.errorOf(word, corpus)));
    }
}
