package io.github.fiftieshousewife.codesemantics.corpus;

import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Renders a pooled corpus as the TSV the reference bundles: a provenance header carrying the manifest that
 * drew the repositories and the weighting this table was pooled under, then one row per word.
 */
public final class PooledVocabularyTsv {

    public static final String COLUMNS = "word\toccurrences\tshare\terror";

    private static final String COLUMN = "\t";

    public String render(final CorpusWords corpus, final DrawnManifest draw, final CorpusPooling pooling) {
        return header(corpus, draw, pooling) + PooledRows.of(corpus, pooling);
    }

    private static String header(final CorpusWords corpus, final DrawnManifest draw,
                                 final CorpusPooling pooling) {
        return """
                # The reference corpus: how densely working Java writes each word, pooled over the
                # repositories a seeded draw took. It is a denominator and nothing else. No row states a
                # subject, nothing here is scored, and a word absent from it has a share of zero.
                #
                """
                + "# Columns: " + COLUMNS.replace(COLUMN, ", ") + ".\n"
                + """
                #   word         as the identifier splitter produced it, from a name a repository declared.
                #   occurrences  how many times the pooled repositories declared it, summed over all of them
                #                and independent of the weighting below.
                #   share        what a reading is read against. It sums to one over this table.
                #   error        the standard error of that share under this table's own weighting - for the
                #                mean of shares, the between-repository standard error of the mean; for
                #                pooled occurrences, the binomial standard error of the proportion. A verdict
                #                whose margin sits inside it has not been shown to stand above chance.
                #
                # WHAT WAS READ. Every tree was read by the path this library reads itself with: the Java
                # source sets, the documentation and the build modules beside them, parsed, split by
                # IdentifierWords, and taken at the stage that keeps the names a repository declared and
                # leaves out the sentences it wrote about them. Both sides of a comparison are therefore made
                # the same way, which is the only thing that makes a share here comparable to a share there.
                #
                """
                + "# HOW IT IS WEIGHTED: " + pooling + " — " + pooling.weighs() + ".\n"
                + "#   One read writes a table per weighting — " + everyTable() + " — so they differ in\n"
                + "#   this line and in the share column alone.\n"
                + "#\n"
                + "# Name: the reference corpus, over words\n"
                + "# Publisher: this library, from a seeded draw of public Java repositories\n"
                + "# Kind: frequencies\n"
                + "# Source: " + draw.name() + ", copied below, which states the frame, the predicate and\n"
                + "#   the seed. Every repository was cloned at the commit it pins.\n"
                + "# Licence: these counts are this project's measurement of publicly available source. Every\n"
                + "#   repository pooled states a licence GitHub recognises, named beside it below.\n"
                + "#\n"
                + "# Generated by CorpusPoolCommand.\n"
                + "# Repositories pooled: " + corpus.repositories()
                + ". Words: " + corpus.words().size()
                + ". Occurrences: " + corpus.totalOccurrences() + ".\n"
                + "#\n"
                + CopiedManifest.of(draw);
    }

    private static String everyTable() {
        return Stream.of(CorpusPooling.values())
                .map(CorpusPooling::fileName)
                .collect(Collectors.joining(", "));
    }
}
