package org.fifties.housewife.codesemantics.model;

/**
 * Identifies which reading produced a vote. Every constant names a resource or a repository fact that can be
 * shown to a reader who asks why — there is no constant for an assertion, because a reading that cannot cite
 * a source abstains rather than voting.
 */
public enum EvidenceSource {

    /** The repository's own statement, in {@code .gitattributes}, that a path is generated. */
    GITATTRIBUTES_GENERATED(EvidenceSourceType.REPOSITORY, "gitattributes-generated"),
    /** The repository's own statement, in {@code .gitattributes}, that a path is vendored. */
    GITATTRIBUTES_VENDORED(EvidenceSourceType.REPOSITORY, "gitattributes-vendored"),
    /** A path whose blobs entered in one large commit and were never subsequently edited. */
    SINGLE_COMMIT_DROP(EvidenceSourceType.REPOSITORY, "single-commit-drop"),
    /** How recently, and by how many distinct authors, a path has been edited. */
    AUTHORSHIP_CONCENTRATION(EvidenceSourceType.REPOSITORY, "authorship-concentration"),

    /** {@code javax.annotation.processing.Generated} — a documented annotation, cited not listed. */
    GENERATOR_ANNOTATION(EvidenceSourceType.CATALOGUE, "generator-annotation"),
    /** The {@code // Code generated by … DO NOT EDIT.} line the Go toolchain specifies. */
    GENERATOR_HEADER(EvidenceSourceType.CATALOGUE, "generator-header"),
    /** The {@code <auto-generated>} element .NET's tooling emits. */
    AUTO_GENERATED_ELEMENT(EvidenceSourceType.CATALOGUE, "auto-generated-element"),
    /** {@code github/linguist}'s own language, vendor and generated data. */
    LINGUIST_DATA(EvidenceSourceType.CATALOGUE, "linguist-data"),
    /** A language specification's own keyword table. */
    LANGUAGE_KEYWORD(EvidenceSourceType.CATALOGUE, "language-keyword"),
    /** A platform's own API index — the standard library's vocabulary rather than this repo's. */
    PLATFORM_API(EvidenceSourceType.CATALOGUE, "platform-api"),
    /** The query language's own function catalogue. */
    QUERY_LANGUAGE_FUNCTION(EvidenceSourceType.CATALOGUE, "query-language-function"),

    /** A WordNet synset the token's lemma belongs to. */
    WORDNET_SENSE(EvidenceSourceType.LEXICON, "wordnet-sense"),
    /** WordNet's most frequent sense for a lemma — the stated no-disambiguation baseline. */
    WORDNET_MOST_FREQUENT_SENSE(EvidenceSourceType.LEXICON, "wordnet-most-frequent-sense"),
    /** The subject domain WordNet Domains assigns a sense. */
    WORDNET_DOMAIN(EvidenceSourceType.LEXICON, "wordnet-domain"),
    /** An expansion a Wiktionary reader has been cited as writing for a token. */
    WIKTIONARY_ABBREVIATION(EvidenceSourceType.LEXICON, "wiktionary-abbreviation"),
    /** A domain Wiktionary's topic labels claim a word for. */
    WIKTIONARY_TOPIC(EvidenceSourceType.LEXICON, "wiktionary-topic"),
    /** An entity the Wikidata registry records a capitals token as a short name of. */
    WIKIDATA_INITIALISM(EvidenceSourceType.LEXICON, "wikidata-initialism"),
    /** A token the Wikidata registry records as a given or family name in some script. */
    WIKIDATA_NAME(EvidenceSourceType.LEXICON, "wikidata-name"),
    /** How common a word is, by rank in the bundled frequency list. */
    WORD_FREQUENCY(EvidenceSourceType.LEXICON, "word-frequency"),
    /** The pooled topical domain of a file or package, read as a prior over its tokens' senses. */
    TOPICAL_DOMAIN(EvidenceSourceType.LEXICON, "topical-domain"),

    /** A sense corroborated by a hypernym chain it shares with a sibling token of the same identifier. */
    SIBLING_TOKEN_HYPERNYM(EvidenceSourceType.GRAMMAR, "sibling-token-hypernym"),
    /** A sense corroborated by the tokens of an enclosing declaration, weighted by scope distance. */
    ENCLOSING_DECLARATION(EvidenceSourceType.GRAMMAR, "enclosing-declaration"),

    /** Words read from a comment, commit message or review body. */
    PROSE_WORD(EvidenceSourceType.PROSE, "prose-word"),
    /** A conventional-commit prefix, cited as the published convention it is. */
    CONVENTIONAL_COMMIT_PREFIX(EvidenceSourceType.PROSE, "conventional-commit-prefix");

    private final EvidenceSourceType type;
    private final String finding;

    EvidenceSource(final EvidenceSourceType type, final String finding) {
        this.type = type;
        this.finding = finding;
    }

    public EvidenceSourceType type() {
        return type;
    }

    public String finding() {
        return finding;
    }

    public String displayName() {
        return type.displayName() + ":" + finding;
    }
}
