package io.github.fiftieshousewife.codesemantics.lexicon.extraction;

import java.util.List;

import io.github.fiftieshousewife.codesemantics.lexicon.SkosConcept;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertAll;

class CweTermsTsvTest {

    @Test
    void carriesTheProvenanceTheBundledFileMustState() {
        final String rendered = new CweTermsTsv().render(
                List.of(new SkosConcept("https://cwe.mitre.org/data/definitions/79.html",
                        "Improper Neutralization of Input During Web Page Generation",
                        "XSS | Cross-Site Scripting", "", "Base", "",
                        "The product does not neutralize user input.", "")),
                "https://github.com/OWASP/cwe-sdk-javascript/tree/abc", "deadbeef");

        assertAll(
                () -> assertThat(rendered).contains("Source:"),
                () -> assertThat(rendered).contains("Licence:"),
                () -> assertThat(rendered).contains("The MITRE Corporation"),
                () -> assertThat(rendered).contains("termsofuse"),
                () -> assertThat(rendered).contains("deadbeef"),
                () -> assertThat(rendered).contains("Generated by CweTermsExtraction: 1 weaknesses."),
                () -> assertThat(rendered).contains("XSS | Cross-Site Scripting"));
    }
}
