package io.github.fiftieshousewife.codesemantics.lexicon.extraction;

import java.util.List;

import io.github.fiftieshousewife.codesemantics.lexicon.SkosConcept;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertAll;

class FpmlTermsTsvTest {

    @Test
    void carriesTheProvenanceTheBundledFileMustState() {
        final String rendered = new FpmlTermsTsv().render(
                List.of(new SkosConcept("urn:Swap", "Swap", "", "Product", "complexType", "ird",
                        "A swap.", "")),
                "https://github.com/handcoded/fpml-toolkit-java/tree/abc", "deadbeef");

        assertAll(
                () -> assertThat(rendered).contains("Source:"),
                () -> assertThat(rendered).contains("Licence:"),
                () -> assertThat(rendered).contains("FpML Public License"),
                () -> assertThat(rendered).contains("International Swaps and Derivatives Association"),
                () -> assertThat(rendered).contains("deadbeef"),
                () -> assertThat(rendered).contains("Generated by FpmlTermsExtraction: 1 complex types."),
                () -> assertThat(rendered).contains("urn:Swap\tSwap\t\tProduct\tcomplexType\tird\tA swap.\t"));
    }
}
