package io.github.fiftieshousewife.bi.lexicon.extraction;

import java.util.List;

import io.github.fiftieshousewife.bi.lexicon.SkosConcept;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertAll;

class FixTermsTsvTest {

    @Test
    void carriesTheProvenanceTheBundledFileMustState() {
        final String rendered = new FixTermsTsv().render(
                List.of(new SkosConcept("urn:SettlDate", "SettlDate", "SettlDt", "", "field", "",
                        "Specific date of trade settlement.", "")),
                "https://github.com/FIXTradingCommunity/orchestrations/tree/abc", "deadbeef");

        assertAll(
                () -> assertThat(rendered).contains("Source:"),
                () -> assertThat(rendered).contains("Licence:"),
                () -> assertThat(rendered).contains("Apache-2.0"),
                () -> assertThat(rendered).contains("deadbeef"),
                () -> assertThat(rendered).contains("Generated by FixTermsExtraction: 1 concepts."),
                () -> assertThat(rendered)
                        .contains("urn:SettlDate\tSettlDate\tSettlDt\t\tfield\t\t"
                                + "Specific date of trade settlement.\t"));
    }
}
