package io.github.fiftieshousewife.bi.lexicon.extraction;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.zip.GZIPOutputStream;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.junit.jupiter.api.Assertions.assertAll;

class OpenAlexTopicsExtractionTest {

    private static final String PART = "s3://openalex/data/jsonl/topics/updated_date=2026-06-26/part_0000.gz";

    private static final String MANIFEST = """
            {"date":"2026-06-26","format":"jsonl","entity":"topics","record_count":1,
             "files":[{"url":"%s","meta":{"content_length":%d,"record_count":1}}]}
            """;

    @TempDir
    private Path directory;

    @Test
    void refusesASnapshotThatIsNotTheOneTheHeaderWouldCite() {
        assertThatThrownBy(() -> new OpenAlexTopicsExtraction().pinned(List.of(
                new ContentDigest.Member(PART, "moved".getBytes(StandardCharsets.UTF_8)))))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("1536cbda3cc11838aaa67ef9c9c5f2b327a8ac8875ad07f306f4da44c16e8048");
    }

    @Test
    void writesEveryLevelAndTopicOfASnapshotItAccepts() throws IOException {
        final Path output = directory.resolve("written").resolve("openalex-topics.tsv");
        extractionOf(snapshot()).extract(directory, output);

        final String written = Files.readString(output);
        assertAll(
                () -> assertThat(written).contains("# Source: OpenAlex's own topics snapshot, "
                        + "s3://openalex/data/jsonl/topics/ at 2026-06-26, the manifest and the 1 parts it "
                        + "names, stating 1 records"),
                () -> assertThat(written).contains("Generated by OpenAlexTopicsExtraction: 4 concepts."),
                () -> assertThat(written).contains("\nT11347\tNeural Networks Stability and Synchronization"
                        + "\t\tsubfields/1705\ttopic\tdomains/3\t"),
                () -> assertThat(written).contains("\ndomains/3\tPhysical Sciences\t\t\tdomain\tdomains/3"),
                () -> assertThat(written).contains("\nfields/17\tComputer Science\t\tdomains/3\tfield"),
                () -> assertThat(written).contains("\nsubfields/1705\tComputer Networks and Communications"
                        + "\t\tfields/17\tsubfield"));
    }

    @Test
    void refusesADirectoryNamingNoManifestRatherThanReadingWhateverIsInIt() {
        assertThatThrownBy(() -> new OpenAlexTopicsExtraction().extract(directory,
                directory.resolve("openalex-topics.tsv")))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("manifest.json or manifest");
    }

    @Test
    void readsAManifestThePublisherServesWithoutASuffix() throws IOException {
        final byte[] part = compressed(OpenAlexTopicTest.RECORD.replace("\n", "") + "\n");
        Files.write(directory.resolve("part_0000.gz"), part);
        final byte[] manifest = MANIFEST.formatted(PART, part.length).getBytes(StandardCharsets.UTF_8);
        Files.write(directory.resolve("manifest"), manifest);

        final Path output = directory.resolve("openalex-topics.tsv");
        extractionOf(digestOf(manifest, part)).extract(directory, output);
        assertThat(Files.readString(output)).contains("T11347");
    }

    /** The digest of the snapshot this test builds, so the acceptance runs over a set the test controls. */
    private String snapshot() throws IOException {
        final byte[] part = compressed(OpenAlexTopicTest.RECORD.replace("\n", "") + "\n");
        Files.write(directory.resolve("part_0000 (1).gz"), part);
        final byte[] manifest = MANIFEST.formatted(PART, part.length).getBytes(StandardCharsets.UTF_8);
        Files.write(directory.resolve("manifest.json"), manifest);
        return digestOf(manifest, part);
    }

    private static String digestOf(final byte[] manifest, final byte[] part) {
        return new ContentDigest().of(List.of(
                new ContentDigest.Member("s3://openalex/data/jsonl/topics/manifest", manifest),
                new ContentDigest.Member(PART, part)));
    }

    private static OpenAlexTopicsExtraction extractionOf(final String digest) {
        return new OpenAlexTopicsExtraction(digest);
    }

    private static byte[] compressed(final String content) throws IOException {
        final ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        try (OutputStream stream = new GZIPOutputStream(bytes)) {
            stream.write(content.getBytes(StandardCharsets.UTF_8));
        }
        return bytes.toByteArray();
    }
}
