package io.github.fiftieshousewife.bi.lexicon.extraction;

import java.util.List;

import io.github.fiftieshousewife.bi.lexicon.SkosConcept;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertAll;

class OpenAlexTopicsTsvTest {

    private static final List<SkosConcept> CONCEPTS = List.of(new SkosConcept("T11347",
            "Neural Networks Stability and Synchronization", "", "subfields/1705", "topic", "domains/3",
            "This cluster of papers focuses on synchronization. Synchronization",
            "https://en.wikipedia.org/wiki/Synchronization_of_coupled_oscillators"));

    private static final String SOURCE = "s3://openalex/data/jsonl/topics/, the 2026-06-26 snapshot";

    private static final String DIGEST = "1536cbda3cc11838aaa67ef9c9c5f2b327a8ac8875ad07f306f4da44c16e8048";

    private final String rendered = new OpenAlexTopicsTsv().render(CONCEPTS, SOURCE, DIGEST);

    @Test
    void statesWhereTheTaxonomyCameFromAndOnWhatTerms() {
        assertAll(
                () -> assertThat(rendered).contains("# Source:"),
                () -> assertThat(rendered).contains(SOURCE),
                () -> assertThat(rendered).contains(DIGEST),
                () -> assertThat(rendered).contains("# Licence: CC0"));
    }

    @Test
    void namesTheColumnsTheRowsAreWrittenIn() {
        assertThat(rendered).contains("# Columns: " + SkosTsv.COLUMNS);
    }

    @Test
    void saysWhatTheDefinitionAndTheNoteHold() {
        assertAll(
                () -> assertThat(rendered).contains("keywords"),
                () -> assertThat(rendered).contains("note is the Wikipedia article"));
    }

    @Test
    void countsWhatItGenerated() {
        assertThat(rendered).contains("Generated by OpenAlexTopicsExtraction: 1 concepts.");
    }

    @Test
    void writesEveryConceptBelowTheHeader() {
        assertThat(rendered).endsWith("T11347\tNeural Networks Stability and Synchronization\t\t"
                + "subfields/1705\ttopic\tdomains/3\tThis cluster of papers focuses on synchronization. "
                + "Synchronization\thttps://en.wikipedia.org/wiki/Synchronization_of_coupled_oscillators\n");
    }
}
